CREATE TABLE public.countries (
    id integer PRIMARY KEY,
    iso_alpha_2 varchar(2) NOT NULL
);

CREATE TABLE public.regions (
    id integer PRIMARY KEY,
    country_id integer NOT NULL REFERENCES public.countries(id),
    region_name varchar(120) NOT NULL,
    enabled boolean NOT NULL
);

CREATE TABLE public.categories (id integer PRIMARY KEY);
CREATE TABLE public.agents (id integer PRIMARY KEY);
CREATE TABLE public.sales_channels (id integer PRIMARY KEY);
CREATE TABLE public.payment_types (payment_type varchar(50) PRIMARY KEY);
CREATE TABLE public.shop_groups (id integer PRIMARY KEY);

CREATE TABLE public.customers (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    login varchar(50) NOT NULL UNIQUE,
    pass varchar(50) NOT NULL,
    business_name varchar(120),
    business_contact_name varchar(100),
    address_street varchar(100) NOT NULL,
    region_id integer REFERENCES public.regions(id),
    address_city varchar(50) NOT NULL,
    address_zip_code varchar(50),
    phone varchar(50),
    phone2 varchar(50),
    website varchar(100),
    email varchar(120) NOT NULL,
    additional_emails jsonb,
    fiscal_code varchar(20),
    vat_country varchar(2),
    vat_number varchar(20),
    newsletter boolean DEFAULT true,
    reg_privacy boolean,
    reg_rules boolean,
    delivery_contact_name varchar(100),
    delivery_business_name varchar(120),
    delivery_address varchar(100),
    delivery_region_id integer REFERENCES public.regions(id),
    delivery_city varchar(50),
    delivery_zip_code varchar(50),
    delivery_phone varchar(50),
    preferred_categories integer[],
    registration_date timestamp without time zone,
    registration_ip varchar(15),
    payment_agreement varchar(100),
    preferred_payment_type varchar(50) REFERENCES public.payment_types(payment_type),
    preferred_language varchar(50),
    fido_granted numeric(10,2) DEFAULT 0.00,
    fido numeric(10,2) DEFAULT 0.00,
    payment_days integer DEFAULT 0,
    payment_days_eom integer DEFAULT -1,
    tax2 numeric(18,2) DEFAULT 0.00,
    shop_location_lat numeric(18,10),
    shop_location_lng numeric(18,10),
    verified boolean DEFAULT false,
    admin_note varchar(250),
    agent_id integer DEFAULT 1 REFERENCES public.agents(id),
    payment_abi varchar(5),
    payment_cab varchar(5),
    payment_iban varchar(34),
    _notes jsonb,
    notes_open integer NOT NULL DEFAULT 0,
    disable_box_discount boolean NOT NULL DEFAULT false,
    last_login_date timestamp without time zone,
    pec varchar(100),
    fiscal_agent_code varchar(45),
    disable_qty_delivery boolean DEFAULT false,
    rma_prepaid boolean DEFAULT true,
    disable_limit_sale boolean DEFAULT false,
    parameters jsonb,
    sales_channel_id integer DEFAULT 1 REFERENCES public.sales_channels(id),
    extra_data jsonb,
    shop_group_ids integer[],
    vies boolean NOT NULL DEFAULT false
);

INSERT INTO public.countries (id, iso_alpha_2) VALUES (1, 'IT');
INSERT INTO public.regions (id, country_id, region_name, enabled)
VALUES (158, 1, 'Forlì-Cesena', true);
INSERT INTO public.categories (id) VALUES (1), (14);
INSERT INTO public.agents (id) VALUES (1), (117);
INSERT INTO public.sales_channels (id) VALUES (1), (13);
INSERT INTO public.payment_types (payment_type) VALUES ('BONIFICO');
INSERT INTO public.shop_groups (id) VALUES (3);
