"""Insert one Life365 customer inside the active synchronization transaction."""

from collections.abc import Mapping

import psycopg
from psycopg import sql
from psycopg.rows import TupleRow

from app.application.exceptions import DBException


async def insert_customer_row(
    cur: psycopg.AsyncCursor[TupleRow], values: Mapping[str, object]
) -> int:
    """Insert prepared column values and return the database-generated ID."""
    if not values:
        raise ValueError("Customer insert needs column values")
    if "id" in values:
        raise ValueError("Customer ID must be generated by PostgreSQL")

    query = sql.SQL(
        "INSERT INTO public.customers ({columns}) VALUES ({values}) RETURNING id"
    ).format(
        columns=sql.SQL(", ").join(sql.Identifier(column) for column in values),
        values=sql.SQL(", ").join(sql.Placeholder(column) for column in values),
    )
    await cur.execute(query, dict(values))
    row = await cur.fetchone()
    if row is None:
        raise DBException("Customer insert returned no ID")
    return row[0]
